"""Core data types for AutoTrader v2.

This module provides fundamental immutable data types used throughout the
AutoTrader system for representing market data, signals, orders, and account state.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


@dataclass(frozen=True, slots=True)
class Bar:
    """Represents a single OHLCV candlestick bar.

    Attributes:
        symbol: Trading symbol (e.g., "AAPL", "BTC/USD").
        timestamp: Bar open time in UTC.
        open: Opening price.
        high: Highest price in the bar period.
        low: Lowest price in the bar period.
        close: Closing price.
        volume: Trading volume in shares/contracts.
    """
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    @property
    def midpoint(self) -> float:
        """Calculate the midpoint between high and low prices.

        Returns:
            Midpoint price: (high + low) / 2
        """
        return (self.high + self.low) / 2


@dataclass(frozen=True, slots=True)
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        strategy: Name of the strategy that generated the signal.
        symbol: Trading symbol for this signal.
        direction: Trade direction - "long", "short", or "close".
        strength: Signal confidence/strength clamped to [0.0, 1.0].
        metadata: Optional additional signal metadata.
    """
    strategy: str
    symbol: str
    direction: Literal["long", "short", "close"]
    strength: float
    metadata: dict = field(default_factory=dict)
    limit_price: float | None = None

    def __post_init__(self):
        """Validate and clamp signal strength to valid range."""
        object.__setattr__(self, "strength", max(0.0, min(1.0, self.strength)))


@dataclass(frozen=True, slots=True)
class Order:
    """Represents an order to be submitted to the broker.

    Attributes:
        symbol: Trading symbol to trade.
        side: Order direction - "buy" or "sell".
        quantity: Number of shares/contracts to trade.
        order_type: Type of order - "market", "limit", "stop", or "stop_limit".
        limit_price: Price for limit orders (required for limit/stop_limit).
        stop_price: Trigger price for stop orders (required for stop/stop_limit).
        time_in_force: Order validity - "day", "gtc" (good-til-canceled), or "ioc" (immediate-or-cancel).
    """
    symbol: str
    side: Literal["buy", "sell"]
    quantity: float
    order_type: Literal["market", "limit", "stop", "stop_limit"]
    limit_price: float | None = None
    stop_price: float | None = None
    time_in_force: Literal["day", "gtc", "ioc"] = "day"


@dataclass(frozen=True, slots=True)
class OrderResult:
    """Result of an order submission to the broker.

    Attributes:
        order_id: Unique order identifier from broker.
        symbol: Trading symbol of the order.
        status: Current order status - "accepted", "filled", "partially_filled", "cancelled", or "rejected".
        filled_qty: Quantity successfully filled.
        filled_price: Average fill price for filled quantity.
    """
    order_id: str
    symbol: str
    status: Literal["accepted", "filled", "partially_filled", "cancelled", "rejected"]
    filled_qty: float = 0.0
    filled_price: float = 0.0


@dataclass(frozen=True, slots=True)
class Position:
    """Represents an open trading position.

    Attributes:
        symbol: Trading symbol of the position.
        quantity: Number of shares/contracts held.
        avg_entry_price: Average entry price for the position.
        market_value: Current market value of the position.
        unrealized_pnl: Unrealized profit/loss in currency units.
        side: Position direction - "long" or "short".
    """
    symbol: str
    quantity: float
    avg_entry_price: float
    market_value: float
    unrealized_pnl: float
    side: Literal["long", "short"]


@dataclass(frozen=True, slots=True)
class AccountInfo:
    """Snapshot of trading account information.

    Attributes:
        account_id: Unique account identifier.
        buying_power: Amount available for new trades.
        portfolio_value: Total value of all holdings and cash.
        cash: Available cash balance.
        equity: Total equity in the account.
    """
    account_id: str
    buying_power: float
    portfolio_value: float
    cash: float
    equity: float


@dataclass(slots=True)
class MarketContext:
    """Current market context for a symbol with indicators and history.

    This is a mutable container (unlike other types) since it represents
    a live trading context that changes frequently.

    Attributes:
        symbol: Trading symbol this context represents.
        bar: Current/latest bar for this symbol.
        indicators: Dictionary of calculated indicators and their values.
                   Values can be floats or nested dicts for complex indicators.
        history: Deque of historical bars for this symbol (for lookback analysis).
    """
    symbol: str
    bar: Bar
    indicators: dict[str, float | dict | None]
    history: deque[Bar]
